### ISSUE TITLE
Build STRUMPACK without Fortran possible ?

### ISSUE THREAD

**Issue by urochanr** [pghysels/STRUMPACK#46]
Hi Strumpack Developers,
I hope this is the place to ask questions about STRUMPACK.
Is it possible to build strumpack without a Fortran compiler ? I tried to but could not do so.
Reason I am asking is that I am using Intel Compiler for C/C++ but do not want to pay extra to buy a Fortran compiler.
Thanks,
Rochan

**Comment by pghysels** [comment]
No, that is not possible at the moment.
But you should be able to use the Intel Compiler for C/C++ and the (free) GCC compiler gfortran for fortran.
These can be mixed, for instance:
```
          -DCMAKE_CXX_COMPILER=icpc \
          -DCMAKE_C_COMPILER=icc \
          -DCMAKE_Fortran_COMPILER=gfortran \
```
Please let me know if you have any issues with that.

**Comment by urochanr** [comment]
Yes I could do that (combination of icpc, icc and gfortran). I was wondering if there will be large impact on the performance on bringing in gfortran. For some reason I see Intel compilers do much better with this Solver (for Sparse Matrices). I do not understand the reason though ... Are there any benchmark results for different compilers ?

**Comment by pghysels** [comment]
I don't think using gfortran instead of the intel fortran compiler should make a big difference. 
I also didn't think there would be a big difference between the Intel C/C++ compilers and GCC gcc/g++.
Are you using the same BLAS/LAPACK versions with the different compilers? The performance is mostly determined by your BLAS/LAPACK library.
Use Intel MKL if you can, or else OpenBLAS. Or ESSL on IBM. Performance will be much worse with the netlib reference implementation.

**Comment by urochanr** [comment]
Yes gfortran use did not make any difference at least wrt another package using the super-nodal method (SuperLU_Dist built purely with Intel MKL etc). I am closing this ticket now. Thank you.
